{{- $fullName := include "gnmic.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    {{- include "gnmic.labels" . | nindent 4 }}
  name: {{ $fullName }}-collector
  namespace: {{ .Release.Namespace }}
{{- with .Values.config.global }}
data:
  gnmic.yml: |
    {{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.config.collector }}
    {{- toYaml . | nindent 6 }}
{{- end }}
{{- if and .Values.autoscaling.enabled (eq .Values.autoscaling.locker "k8s") }}
      api: ":7890"
      clustering:
        cluster-name: {{ $fullName }}-collector
        locker:
          type: k8s
          namespace: {{ .Release.Namespace }}
{{- end }}
{{- if and .Values.autoscaling.enabled (eq .Values.autoscaling.locker "consul") }}
      api: ":7890"
      clustering:
        cluster-name: {{ $fullName }}-collector
        leader-wait-timer: 60s
        locker:
          type: consul
          address: {{ $fullName }}-consul-svc:8500
{{- end }}
{{- if .Values.server.enabled }}
      gnmi-server:
        address: ":{{ .Values.server.port }}"
        debug: false
        cache:
        {{- with .Values.server.cache }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}