{{- if .Values.autoscaling.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gnmic.fullname" . }}-rebalance-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gnmic.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "gnmic.labels" . | nindent 12 }}
          name: {{ include "gnmic.fullname" .}}-rebalance-cronjob
          {{- with .Values.cronjob.annotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          containers:
          command: ["/bin/sh","-c"]
          - args:
            - apk add jq curl && curl -s -X POST `curl -s {{ include "gnmic.fullname" . }}-collector-gnmic-api:{{ .Values.service.port }}/api/v1/cluster |  jq .leader | tr -d '"' | {read x; echo "${x}.{{ include "gnmic.fullname" . }}"}`:{{ .Values.service.port }}/api/v1/cluster/rebalance
            image: alpine
            imagePullPolicy: IfNotPresent
            name: {{ include "gnmic.fullname" . }}-rebalance
          image: alpine
          restartPolicy: Never
  schedule: "* * * * *"
{{- end }}