{{- if .Values.secrets.opaque.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gnmic.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets.opaque.items }}
  {{ $k }}: {{ $v }}
  {{- end }}
{{- end }}