apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnmic.fullname" . }}-relay-gnmic-api
  labels:
    {{- include "gnmic.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy:  {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7890
      protocol: TCP
      name: gnmi-api-relay
  selector:
    {{- include "gnmic.selectorLabels" . | nindent 4 }}
    instance: relay
