{{ if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.kafka.user.name }}
  {{- if .Values.kafka.kafka_namespace }}
  namespace: {{ .Values.kafka.kafka_namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "gnmic.labels" . | nindent 4 }}
    {{- if .Values.kafka.cluster }}
    strimzi.io/cluster: {{ .Values.kafka.cluster }}
    {{- else }}
    strimzi.io/cluster: {{ .Release.Namespace }}-kafka
    {{- end }}
spec:
  {{- if .Values.kafka.kafka_namespace }}
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .Release.Namespace }}
  {{- end}}
  authentication:
    type: {{ .Values.kafka.user.mechanism }}
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ .Values.kafka.topic.name }}
          patternType: literal
        operations:
          - Describe
          - Create
          - Read
          - Write
          - Delete
        host: "*"
      - resource:
          type: group
          name: {{ .Values.kafka.group }}-collector
          patternType: literal
        operations:
          - Describe
          - Create
          - Read
          - Write
          - Delete
        host: "*"
      - resource:
          type: group
          name: {{ .Values.kafka.group }}-relay
          patternType: literal
        operations:
          - Describe
          - Create
          - Read
          - Write
          - Delete
        host: "*"
{{- end }}
